---

- name: Check if there are any previous entries in resolv.conf
  find:
    paths: /etc/resolv.conf
    patterns: '^nameserver ([0-9]{1,3}\.){1,3}[0-9]{1,3}$'
  register: found_previous

- name: Set up resolv.conf (non-verride).
  template:
    src: "{{ item }}"
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
  with_first_found:
    - files:
        - "{{ 'hostname_' + inventory_hostname + '.j2' }}"
        - resolv.j2
  paths:
    - ../templates
  when: (found_previous is not defined and replace_previous == 1) or replace_previous == 0

- name: Set up resolv.conf (override or non-existent).
  template:
    src: "{{ item }}"
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
  with_first_found:
    - files:
        - "{{ 'hostname_' + inventory_hostname + '.j2' }}"
        - resolv.j2
  paths:
    - ../templates
  when: (found_previous is defined) and (replace_previous == 1)
