---
- name: Check if there are any previous entries in resolv.conf.
  command: "egrep ^nameserver /etc/resolv.conf"
  register: resolv_conf_records
  failed_when: False
  changed_when: False

- name: Set up resolv.conf (non-existent records).
  template:
    src: "resolv.conf.j2"
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
  when: >
    __resolv_conf_records | length == 0

- name: Set up resolv.conf (append to current records).
  lineinfile:
    path: /etc/resolv.conf
    line: "nameserver {{ item }}"
  loop: "{{ resolv_conf_nameservers }}"
  when: >
    __resolv_conf_records | length > 0
...
